import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryClientProvider from "@/components/global/ReactQueryClientProvider";
import JobDashThemeProvider from "@/components/global/JobDashThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<JobDashThemeProvider>
			<ReactQueryClientProvider>
				<html lang="en">
					<body className={inter.className}>{children}</body>
				</html>
			</ReactQueryClientProvider>
		</JobDashThemeProvider>
	);
}
